version: 2

sphinx:
  configuration: docs/source/conf.py
  fail_on_warning: false

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.8"
    
python:
  install:
    - requirements: requirements.txt
    - requirements: dev-requirements.txt
